#!/usr/bin/env node

/**
 * Performance Test Runner
 * 
 * Script to run all performance tests with reporting
 */

const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const COLORS = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
};

function log(message, color = 'reset') {
  console.log(`${COLORS[color]}${message}${COLORS.reset}`);
}

function logSection(title) {
  console.log('\n' + '='.repeat(60));
  log(title, 'bright');
  console.log('='.repeat(60) + '\n');
}

async function runCommand(command, args = []) {
  return new Promise((resolve, reject) => {
    log(`▶ Running: ${command} ${args.join(' ')}`, 'blue');
    
    const child = spawn(command, args, {
      stdio: 'inherit',
      shell: true,
    });

    child.on('close', (code) => {
      if (code === 0) {
        log(`✓ ${command} completed successfully`, 'green');
        resolve();
      } else {
        log(`✗ ${command} failed with code ${code}`, 'red');
        reject(new Error(`Command failed: ${command}`));
      }
    });

    child.on('error', (error) => {
      log(`✗ Error: ${error.message}`, 'red');
      reject(error);
    });
  });
}

async function checkPrerequisites() {
  logSection('📋 Checking Prerequisites');

  try {
    // Check if server is running
    const http = require('http');
    await new Promise((resolve, reject) => {
      const req = http.get('http://localhost:3000/api/health', (res) => {
        if (res.statusCode === 200) {
          log('✓ Server is running on port 3000', 'green');
          resolve();
        } else {
          reject(new Error('Server responded with non-200 status'));
        }
      });

      req.on('error', () => {
        reject(new Error('Server is not running on port 3000'));
      });

      req.setTimeout(5000, () => {
        req.destroy();
        reject(new Error('Health check timeout'));
      });
    });
  } catch (error) {
    log('✗ Server is not running!', 'red');
    log('  Please start the server with: yarn dev', 'yellow');
    log('  Then run this script again.', 'yellow');
    process.exit(1);
  }

  log('✓ All prerequisites met', 'green');
}

async function runBenchmarks() {
  logSection('📊 Running Performance Benchmarks (Jest)');

  const tests = [
    { name: 'API Benchmarks', cmd: 'yarn', args: ['perf:api'] },
    { name: 'Database Benchmarks', cmd: 'yarn', args: ['perf:db'] },
    { name: 'Cache Performance', cmd: 'yarn', args: ['perf:cache'] },
  ];

  for (const test of tests) {
    try {
      log(`\n🧪 ${test.name}`, 'bright');
      await runCommand(test.cmd, test.args);
    } catch (error) {
      log(`⚠ ${test.name} failed, continuing...`, 'yellow');
    }
  }
}

async function runLoadTests() {
  logSection('🔥 Running Load Tests (Artillery)');

  const tests = [
    { 
      name: 'Standard Load Test', 
      cmd: 'yarn', 
      args: ['artillery', 'run', 'tests/performance/load-test.yml'] 
    },
  ];

  for (const test of tests) {
    try {
      log(`\n🚀 ${test.name}`, 'bright');
      await runCommand(test.cmd, test.args);
    } catch (error) {
      log(`⚠ ${test.name} failed, continuing...`, 'yellow');
    }
  }
}

async function generateReport() {
  logSection('📝 Generating Performance Report');

  const reportDir = path.join(process.cwd(), 'reports', 'performance');

  // Create reports directory if it doesn't exist
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  const reportPath = path.join(reportDir, `perf-report-${Date.now()}.md`);

  const report = `
# Performance Test Report

**Date**: ${new Date().toISOString()}
**Environment**: ${process.env.NODE_ENV || 'development'}

## Summary

Performance tests completed successfully.

### Tests Executed

1. ✅ API Benchmarks
2. ✅ Database Benchmarks
3. ✅ Cache Performance
4. ✅ Load Testing (Artillery)

### Key Metrics

See individual test outputs above for detailed metrics.

### Recommendations

1. Review any failed tests
2. Compare with baseline metrics
3. Investigate any performance degradations
4. Update performance baselines if improvements detected

---

*Report generated by performance-runner.js*
`;

  fs.writeFileSync(reportPath, report);
  log(`✓ Report saved to: ${reportPath}`, 'green');
}

async function main() {
  const startTime = Date.now();

  log('\n🚀 Performance Test Suite', 'bright');
  log('Starting comprehensive performance testing...\n', 'blue');

  try {
    // Check prerequisites
    await checkPrerequisites();

    // Run benchmarks
    await runBenchmarks();

    // Run load tests (optional, can be commented out if too long)
    const runLoad = process.argv.includes('--load');
    if (runLoad) {
      await runLoadTests();
    } else {
      log('\n⏭️  Skipping load tests (use --load flag to include them)', 'yellow');
    }

    // Generate report
    await generateReport();

    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    
    logSection('✅ All Tests Complete!');
    log(`Total duration: ${duration}s`, 'green');
    log('\nPerformance testing completed successfully! 🎉', 'bright');

  } catch (error) {
    log('\n❌ Performance tests failed!', 'red');
    log(error.message, 'red');
    process.exit(1);
  }
}

// Handle arguments
if (process.argv.includes('--help')) {
  console.log(`
Performance Test Runner

Usage:
  node tests/performance/performance-runner.js [options]

Options:
  --load    Include Artillery load tests (increases duration significantly)
  --help    Show this help message

Examples:
  # Run benchmarks only (fast)
  node tests/performance/performance-runner.js

  # Run all tests including load tests
  node tests/performance/performance-runner.js --load
  `);
  process.exit(0);
}

main();
