FROM node:slim AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Runtime image
FROM node:slim
WORKDIR /app

COPY --from=builder /app ./
ENV NODE_ENV=production

RUN npm install --omit=dev
EXPOSE 3000

CMD ["npm", "run", "start"]
